services:
  htwd-checker:
    build: .
    container_name: htwd-checker-${HTWD_USERNAME}
    restart: unless-stopped
    env_file:
      - users/${HTWD_USERNAME}.env
    volumes:
      - ./logs/${HTWD_USERNAME}:/app/logs
    mem_limit: 256m
