services:
    htwd-checker:
        build: .
        container_name: htwd-checker
        restart: unless-stopped
        env_file:
            - .env
        volumes:
            - ./logs:/app/logs
        mem_limit: 256m
